# Generated by Django 5.0.7 on 2024-08-03 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Proveedor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('exportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.exportador', verbose_name='Exportador')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compras_efectivas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Compras Efectivas')),
                ('saldos_iniciales', models.IntegerField(blank=True, default=0, null=True, verbose_name='Saldos Iniciales')),
                ('salidas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Salidas')),
                ('traslado_propio', models.IntegerField(blank=True, default=0, null=True, verbose_name='Traslado Propio')),
                ('traslado_remisionado', models.IntegerField(blank=True, default=0, null=True, verbose_name='Traslado Remisionado')),
                ('ventas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ventas')),
                ('venta_contenedor', models.IntegerField(blank=True, default=0, null=True, verbose_name='Venta Contenedor')),
                ('numero_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.referencias', verbose_name='Referencia')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_historico', models.CharField(max_length=100)),
                ('cantidad_cajas_h', models.IntegerField(verbose_name='Cantidad Cajas')),
                ('propiedad', models.CharField(max_length=50, verbose_name='Propiedad')),
                ('fecha_movimiento', models.DateField(verbose_name='Fecha Movimiento')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Historico')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.bodega', verbose_name='Bodega')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cajas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Cajas')),
                ('tipo_documento', models.CharField(choices=[('Factura', 'Factura'), ('Remisión', 'Remisión'), ('Acta De Destrucción', 'Acta De Destrucción'), ('Saldo Inicial', 'Saldo Inicial')], max_length=20, verbose_name='Tipo Documento')),
                ('documento', models.CharField(max_length=100, verbose_name='Documento')),
                ('fecha_movimiento', models.DateField(verbose_name='Fecha Movimiento')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.bodega', verbose_name='Tipo De Movimiento')),
                ('numero_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.referencias', verbose_name='Referencia')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.exportador', verbose_name='Propiedad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.proveedor', verbose_name='Proveedor O Tercero')),
            ],
        ),
    ]
