# Generated by Django 5.0.7 on 2024-08-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='no_cajas_nc',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='No Cajas NC'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_proforma',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='$Proforma'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='no_cajas_nc',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='No Cajas NC'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='precio_proforma',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='$Proforma'),
        ),
    ]
